BUILD_SCRIPTS := $(abspath $(CURDIR)/../buildscripts)

# Project files:
PPC_BIN = patch
PPC_OBJS = patch.o cache.o common.o debug.o ppc_mon.o

include $(BUILD_SCRIPTS)/ppc/Defs.make
include $(BUILD_SCRIPTS)/ppc/Rules.bin.make
include $(BUILD_SCRIPTS)/ppc/Rules.make